### ISSUE TITLE
phpBB Gallery 1.0.5 to phpBB 3.1

### ISSUE THREAD

**Issue by KoshaK0** [nickv-phpbb/howto-convert-phpbb30mod-to-phpbb31ext#7]
Hi,

is there is the way to migrate from old Gallery to new?
I had phpBB 3.0.x board with Gallery 1.0.5
now trying to update to phpBB 3.1.3

Can you pls advice, or if you can do it for me the reward?

Regards,
Kos

**Comment by wintstar** [comment]
Please look here => https://www.phpbb.com/community/viewtopic.php?f=456&t=2273501
